### ISSUE TITLE
Invalid HTTP method with nginx proxy

### ISSUE THREAD

**Issue by Rinma** [turtl/api#32]
I try to use nginx as a prox for the turtl server with this configuration:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    listen 443 ssl;

    server_name turtl.local.host;

    access_log  /var/log/nginx/turtl_access.log;
    error_log   /var/log/nginx/turtl_error.log;

    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }

    ssl_certificate /etc/letsencrypt/live/turtl.local.host/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/turtl.local.host/privkey.pem;

    ssl on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_timeout 5m;

     location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass https://127.0.0.1:8181;
        proxy_redirect off;
    }

}
```
When I now try to create an account with the desktop or android app I get the following error:

```
<ERROR> [1487521615] wookie - error parsing: INVALID-METHOD: invalid HTTP method
  <INFO> [1487521615] wookie - "GET NIL" 400 33
 <DEBUG> [1487521615] turtl - turtl error: INVALID-METHOD: invalid HTTP method
 <ERROR> [1487521615] turtl - listener: INVALID-METHOD: invalid HTTP method
 <DEBUG> [1487521615] turtl - turtl error: #<SOCKET-EOF #<TCP-SOCKET #x302003070FCD>: 0: NIL #x3020030653BD>
```
The server gets start inside a docker container and when i expose the port not only to localhost i can use the server adress with the turtle container port and everythings works fine.
I start the container like this:
```
version: '2'
services:
    turtl:
        build:
           context: ./turtl-docker
           dockerfile: Dockerfile
        environment:
            - FQDN=turtl.local.host
            - SITE_URL=https://turtl.local.host
            - ADMIN_EMAIL=server@local.host
            - EMAIL_FROM=noreply@local.host
            - SMTP_USER=server
            - SMTP_PASS=password
        ports:
            - '0.0.0.0:8181:8181'
```
Everything should work fine with the proxy when i get the instructions right.
